language: node_js
node_js:
  - '6'
services:
  - postgresql
addons:
  - postgresql: "9.6"
before_script:
  - psql -c 'create database to-fix-test;' -U postgres
  - psql -U postgres -d to-fix-test -c "create extension postgis;"
